source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'mysql2', '0.3.18'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', ' ~> 2.7.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails', '~> 4.0.3'
gem 'turbolinks', '~> 2.5.3'
gem 'jbuilder', '~> 2.2.8'
gem 'sdoc', '~> 0.4.0', group: :doc

# gem 'capistrano-rails', group: :development

group :development, :test do
  gem 'byebug', '~> 3.5.1'
  gem 'web-console', '~> 2.1.0'
  gem 'spring', '~> 1.3.3'
end

gem 'haml-rails', '~> 0.8.2'
gem 'bootstrap-sass', '~> 3.3.3'
gem 'font-awesome-rails', '~> 4.3.0'
gem 'autoprefixer-rails', '~> 5.1.7'
gem 'puma', '~> 2.11.1'
gem 'devise', '~> 3.4.1'
gem 'faye-websocket', '~> 0.9.2'
gem 'pry', '~> 0.10.1'
gem 'hirb', '~> 0.7.3'
gem 'date_validator', '~> 0.7.1'

group :development do
  gem 'guard-livereload', '~> 2.4.0'
end

group :test do
  gem 'database_cleaner', '~> 1.4.0'
  gem 'timecop', '~> 0.7.3'
  gem 'pry-byebug', '~> 3.0.1'
end
